//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cityy
    {
        
        public Cityy()
        {
            this.Routee = new HashSet<Routee>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
       
        public virtual ICollection<Routee> Routee { get; set; }
    }
}
