//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Human> HumanSet { get; set; }
        public virtual DbSet<Permit> PermitSet { get; set; }
        public virtual DbSet<route> routeSet { get; set; }
        public virtual DbSet<Country> CountrySet { get; set; }
        public virtual DbSet<city> citySet { get; set; }
        public virtual DbSet<Hotel> HotelSet { get; set; }
    }
}
