//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicce
    {
        
        public Servicce()
        {
            this.Hotell = new HashSet<Hotell>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
    
        
        public virtual ICollection<Hotell> Hotell { get; set; }
    }
}
